# file      : tests/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

if! $cxx.features.modules
{
  # List sources as files so that we can prepare a distribution with any
  # compiler.
  #
  ./: cxx{*} file{test.out}
}
else
{
  import libs = libstd-modules%liba{std-modules}

  exe{driver}: cxx{driver} $libs
  exe{driver}: file{test.out}: test.stdout = true
}
