# file      : tests/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libstd-modules%liba{std-modules}

exe{driver}: cxx{driver} $libs
exe{driver}: test.output = test.out
